### PR TITLE
Install nanoflann arch-independently again

### PR DESCRIPTION
**Pull request by roehling**
This is a tweak for PR #131 that undid the effect of PR #130 by
accident.

### CODE REVIEW

**Comment by jlblancoc** [comment]
cc: @mablanchard

**Comment by mablanchard** [comment]
> This is a tweak for PR #131 that undid the effect of PR #130 by accident.

The [pkg-config project recommandation](https://gitlab.freedesktop.org/pkg-config/pkg-config/-/blob/master/pkg-config.1#L525) is to install metadata files to `libdir` but as nanoflann probably is arch. independent, I guess it's fine to install to `datadir`. Feels weird to me to consider code as an arch. independent data though, but that is opinion.

**Comment by jlblancoc** [comment]
For curiosity, I checked how this was handled in libeigen3-dev, which is also header-only: 
https://packages.debian.org/stretch/all/libeigen3-dev/filelist

It's stored in `/usr/share/pkgconfig/eigen3.pc`.

**Comment by roehling** [comment]
> Feels weird to me to consider code as an arch. independent data though, but that is opinion.

If it makes you feel any better: technically, pkg-config .pc files are more like configuration files than code ;-)

**Pull request merged**
